### ISSUE TITLE
Help a noob

### ISSUE THREAD

**Issue by dogofpavlov** [alexander-alegre/electron-with-typescript#1]
Hi Alexander, thank you very much for creating this. I'm a complete noob to Electron but not as much with create-react-app. This project has greatly helped my understanding of how to use them together.

I'm attempting to build a multi-window application with Electron and would like to use this as a starting point. Do you think that's a good idea? 

Also is it possible for the "electron-starter.js" to be Typescript? 

Also Also, I'd like to use a few classes I wrote in the "src" inside of the "electron-starter.js" but I can't seem to figure out the path. I've tried:

const MyClass = require('./src/MyClass');
const MyClass = require('src/MyClass');
const MyClass = require('MyClass');

and all a lot of other variations but always got an error.

One thing I don't quite understand is how I could possibly share data between "electron-starter" and the "App.tsx".

Thanks again for your library and your time.

**Comment by alexander-alegre** [comment]
Hey there, thanks for taking a look at this. After I made this i discovered a new tool which is what I will recommend. It is called Electron Forge. It's CRA but for electron and it has many prebuilt templates including a React with TS template.
[https://electronforge.io/templates](https://electronforge.io/templates)
Check out that link and it will provide the commands you need to run.

As far as sharing the data it's not as easy as a regular JS/TS app where you can just do an import. The files in the React app can be seen as the front end file and the other one which start the electron server and so on can be seen as the server. You don't need to make any HTTP requests but electron has messages you need to request and send from each side of the app.
This would go on your main.ts file (server) and it will send a message to the React app.
`import {ipcMain} from 'electron';`
`ipcMain.emit('some-message-name', {data});`
This is how the React app listens to said message
`import {ipcRenderer} from 'electron';`
`ipcRenderer.on('some-message-name', (data) => { /* do stuff with data */});`

Here is a link to their docs and the other ways you can use these.

[ipcMain](https://electronjs.org/docs/api/ipc-main)
[ipcRendered](https://electronjs.org/docs/api/ipc-renderer)

Hope this helps! Good luck building your app!

## Alex

**Comment by dogofpavlov** [comment]
thanks for the quick reply. I will definitely check out Electron Forge. Appreciate the tips and comments
